(()=>{'use strict';
const api=window.SantiArcade,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],save=api.save;
const EVENTS=[
 ['TRAINING CAMP','training','🏟️'],['BASKETBALL — LEARN','basketball','🏀'],['BASKETBALL — MATCH','basketball','🏀'],['SOCCER — LEARN','soccer','⚽'],['SOCCER — MATCH','soccer','⚽'],['FOOTBALL — LEARN','football','🏈'],['FOOTBALL — MATCH','football','🏈'],['BASEBALL — LEARN','baseball','⚾'],['BASEBALL — MATCH','baseball','⚾'],['CHAMPIONSHIP','championship','🏆']
];
const MATH_NAMES={add:'Addition',sub:'Subtraction',mix:'Mixed Addition & Subtraction',groups:'Multiplication Concept',times2:'×2 Facts',times5:'×5 Facts',final:'×10 Facts'};
const ACHIEVEMENTS={mathSkill:['➕','MATH SKILL MASTERED','Master a City Quest math skill.'],firstChampionship:['🏆','FIRST CHAMPIONSHIP','Win your first Spelling Championship.'],words10:['🔤','10 WORDS MASTERED','Master 10 spelling words.'],words50:['📚','50 WORDS MASTERED','Master 50 spelling words.'],words100:['🌟','100 WORDS MASTERED','Master 100 spelling words.'],streak10:['🔥','10 ANSWER STREAK','Spell 10 words correctly in a row.'],basketballStar:['🏀','BASKETBALL STAR','Shine on the basketball court.'],soccerStar:['⚽','SOCCER STAR','Score like a soccer champion.'],touchdownStar:['🏈','TOUCHDOWN STAR','Complete a perfect football drive.'],homeRunHero:['⚾','HOME RUN HERO','Hit a stadium home run.'],citySeason1:['🌆','CITY EXPLORER CUP','Complete City Quest Season 1.']};
let lastAchievement=null,wordBank=null,sports=null,shareType='progress',cityMusicTimer=0;

function persist(){api.persist();syncPlatform()}
function cityMissionTotal(){return Object.values(save.city.seasons||{}).reduce((total,s)=>total+Object.values(s.levels||{}).reduce((n,l)=>n+Object.values(l.missions||{}).filter(Boolean).length,0),0)}
function masteredMath(){return Object.values(save.city.mathMastery||{}).filter(x=>x.status==='MASTERED').length}
function syncPlatform(){
 if(!save.player)return;
 CitySeasons.ensure(save);const target=CitySeasons.continueTarget(save),level=target.level,event=Math.min(10,save.spelling.event||1);
 $('#city-progress').textContent=`Season ${target.season} • Level ${level}/10`;
 $('#spelling-progress').textContent=save.spelling.championships?`Season ${save.spelling.season} Champion`:`Season 1 • Event ${event}/10`;
 $('#next-goal strong').textContent=save.spelling.wordsMastered<3?`Master ${3-save.spelling.wordsMastered} more spelling words`:level<10?`Complete City Quest Level ${level}`:'Play the Spelling Championship';
 if($('#profile-name')){$('#profile-name').textContent=save.player.nickname.toUpperCase();api.drawAvatar($('#profile-avatar'),save.player.avatar);renderProfile()}
}
window.addEventListener('santi:save-sync',syncPlatform);
function renderProfile(){
 const cityTarget=CitySeasons.continueTarget(save),best=Math.max(0,save.spelling.bestStreak||0),stats=[['🌆','CITY QUEST',`Season ${cityTarget.season} • Level ${cityTarget.level}/10`],['🏟️','SPELLING',`Season ${save.spelling.season} • Event ${Math.min(10,save.spelling.event)}/10`],['➕','MATH SKILLS',`${masteredMath()} mastered`],['🔤','WORDS',`${save.spelling.wordsMastered} mastered`],['🏆','CHAMPIONSHIPS',`${save.city.championships+save.spelling.championships}`],['🔥','BEST STREAK',`${best}`]];
 $('#profile-stats').innerHTML=stats.map(x=>`<article><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join('');
 const all=[...save.collection.trophies.map(x=>['🏆',x]),...save.collection.badges.map(x=>['🎖️',x]),...save.collection.gear.map(x=>['🎧',x]),...save.collection.cards.map(x=>['🃏',x])];
 $('#collection-grid').innerHTML=all.length?all.map(x=>`<article><span>${x[0]}</span><strong>${x[1]}</strong></article>`).join(''):'<p class="empty-collection">Play and learn to unlock trophies, badges, gear, and cards!</p>';
}
function unlock(key){if(save.achievements[key])return;save.achievements[key]=true;const a=ACHIEVEMENTS[key];if(!a)return;save.collection.badges.push(a[1]);lastAchievement={key,icon:a[0],name:a[1],copy:a[2]};persist();$('#achievement-icon').textContent=a[0];$('#achievement-name').textContent=a[1];$('#achievement-copy').textContent=a[2];$('#achievement-panel').classList.remove('hidden');api.sfx.unlock()}

window.addEventListener('santi:math-result',e=>{const key=e.detail.skill,before=save.city.mathMastery[key]?.status,m=CitySeasons.updateMathMastery(save.city.mathMastery[key],e.detail.rewarded);save.city.mathMastery[key]=m;persist();if(before!=='MASTERED'&&m.status==='MASTERED')unlock('mathSkill')});
window.addEventListener('santi:city-level',e=>startCityMotif(e.detail.level,e.detail.season,e.detail.motif));
window.addEventListener('santi:city-level-end',stopCityMotif);
window.addEventListener('santi:city-season-champion',e=>{const a=e.detail;lastAchievement={key:`citySeason${a.season}`,icon:'🏆',name:`${a.name} CHAMPION`,copy:`Season ${a.nextSeason} is ready!`};persist();$('#achievement-icon').textContent='🏆';$('#achievement-name').textContent=lastAchievement.name;$('#achievement-copy').textContent=lastAchievement.copy;$('#achievement-share').classList.remove('hidden');$('#achievement-panel').classList.remove('hidden');api.sfx.unlock()});
function startCityMotif(level,season=1,motif=0){stopCityMotif();const sets=[[523,659,784],[392,523,659],[440,554,740],[330,494,659],[262,392,523,784]],notes=sets[season>=5?motif%sets.length:Math.min(4,Math.floor((level-1)/2)+(season-1))%sets.length];let n=0;cityMusicTimer=setInterval(()=>{if(save.musicOn)api.tone(notes[n++%notes.length],.15,season===3?'square':'triangle',.012)},1400)}
function stopCityMotif(){clearInterval(cityMusicTimer);cityMusicTimer=0}

function openProfile(){api.show('profile-screen');syncPlatform();coach('player','👤','THIS IS YOUR PLAYER','Change your avatar, see progress, and share achievements here.')}
$$('.global-player').forEach(b=>b.addEventListener('click',openProfile));
$('#profile-edit').onclick=api.openPlayerEditor;
$('#share-progress-btn').onclick=()=>openShare('progress');
$('#spelling-card').onclick=()=>{api.wakeAudio();api.show('spelling-map-screen');renderEventMap();coach('sports','🏟️','WELCOME TO SPORTS WORLD','Listen, spell, earn power, and score!')};

function renderEventMap(){const box=$('#event-map'),current=save.spelling.event||1;box.innerHTML=EVENTS.map((e,i)=>{const n=i+1,locked=n>current,stars=save.spelling.events[n]?.stars||0;return `<button data-event="${i}" ${locked?'disabled':''} class="event-node ${locked?'locked':''}"><span>${locked?'🔒':e[2]}</span><strong>${n}. ${e[0]}</strong><small>${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</small></button>`}).join('');$$('[data-event]').forEach(b=>b.onclick=()=>startEvent(Number(b.dataset.event)));$('#sports-season-stats').textContent=`${save.spelling.wordsMastered} WORDS MASTERED • BEST STREAK ${save.spelling.bestStreak}`}

function loadWordBank(){if(wordBank)return Promise.resolve(wordBank);return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='data/grade3-words.js?v=0.6.0';script.onload=()=>{wordBank=window.SANTI_WORD_BANK||[];resolve(wordBank)};script.onerror=reject;document.head.appendChild(script)})}
function selectWord(eventIndex){const recent=new Set(save.spelling.lastWords.slice(-5)),records=save.spelling.wordMastery;
 const candidates=wordBank.filter(w=>!recent.has(w.word)&&w.difficulty<=1+Math.floor(eventIndex/3)+1).sort((a,b)=>{const ar=records[a.word],br=records[b.word];const ap=ar?.state==='MASTERED'?3:ar?.state==='CHALLENGE'?2:ar?.state==='PRACTICING'?1:0,bp=br?.state==='MASTERED'?3:br?.state==='CHALLENGE'?2:br?.state==='PRACTICING'?1:0;return ap-bp||Math.random()-.5});
 const word=candidates[0]||wordBank[Math.floor(Math.random()*wordBank.length)];save.spelling.lastWords.push(word.word);save.spelling.lastWords=save.spelling.lastWords.slice(-8);persist();return word}
function startEvent(index){loadWordBank().then(()=>{const event=EVENTS[index],champ=index===9; sports={index,event,name:event[0],sport:event[1],round:0,total:champ?12:3,score:0,stars:0,power:false,tries:0,hinted:false,phase:0,playing:false,streak:save.spelling.currentStreak||0};api.show('spelling-game-screen');$('#sports-event-label').textContent=event[0];$('#sports-result').classList.add('hidden');api.setMusic('');crowd('open');nextSpelling()}).catch(()=>{$('#spell-feedback').textContent='Words are resting offline. Please try again from the event map.'})}
function eventSport(){return sports.sport==='championship'?['basketball','soccer','football','baseball'][Math.floor(sports.round/3)]:sports.sport==='training'?['basketball','soccer','football'][sports.round%3]:sports.sport}
function nextSpelling(){if(sports.round>=sports.total)return finishEvent();sports.word=selectWord(sports.index);const rec=save.spelling.wordMastery[sports.word.word];sports.mode=rec?.state==='MASTERED'&&sports.word.builder?'builder':rec?.state==='PRACTICING'||rec?.state==='CHALLENGE'?'build':'fill';sports.tries=0;sports.hinted=false;sports.built='';sports.power=false;sports.playing=false;$('#sports-score-label').textContent=`${sports.round} / ${sports.total}`;$('#spelling-panel').classList.remove('hidden');$('#sports-action').classList.add('hidden');$('#spell-feedback').textContent='';$('#spell-undo').classList.toggle('hidden',sports.mode==='fill');$('#spell-skip').classList.toggle('hidden',sports.mode!=='builder');renderSpelling();speakWord()}
function renderSpelling(){const w=sports.word.word.toUpperCase(),bank=$('#letter-bank');$('#spell-mode').textContent=sports.mode==='fill'?'FILL THE WORD':sports.mode==='build'?'BUILD THE WORD':'WORD BUILDER BONUS';
 if(sports.mode==='fill'){const candidates=[...new Set([w[Math.max(1,Math.floor(w.length/2))],...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'].sort(()=>Math.random()-.5).slice(0,3))].slice(0,4).sort(()=>Math.random()-.5),pos=Math.max(1,Math.floor(w.length/2));sports.missing=pos;$('#spell-prompt').textContent=w.split('').map((c,i)=>i===pos?'_':c).join(' ');bank.innerHTML=candidates.map(c=>`<button data-letter="${c}">${c}</button>`).join('')}
 else{const letters=w.split('').sort(()=>Math.random()-.5);sports.letters=letters;$('#spell-prompt').textContent=sports.built||'_ '.repeat(w.length);bank.innerHTML=letters.map((c,i)=>`<button data-letter="${c}" data-index="${i}" ${sports.used?.includes(i)?'disabled':''}>${c}</button>`).join('')}
 $$('[data-letter]').forEach(b=>b.onclick=()=>chooseLetter(b.dataset.letter,Number(b.dataset.index)))}
function chooseLetter(letter,index){if(sports.mode==='fill'){checkSpelling(letter===sports.word.word[sports.missing].toUpperCase());return} sports.used=sports.used||[];if(sports.used.includes(index))return;sports.used.push(index);sports.built+=letter;renderSpelling();if(sports.built.length===sports.word.word.length)checkSpelling(sports.built.toLowerCase()===sports.word.word)}
function checkSpelling(ok){sports.tries++;if(ok){const first=sports.tries===1&&!sports.hinted;sports.power=first;sports.streak=first?sports.streak+1:0;save.spelling.currentStreak=sports.streak;save.spelling.bestStreak=Math.max(save.spelling.bestStreak,sports.streak);updateWordMastery(sports.word,first);$('#spell-feedback').textContent=first?'PERFECT! ⚡ POWER PLAY!':'NICE WORK!';api.sfx.correct();setTimeout(beginSport,650);if(sports.streak>=10)unlock('streak10')}else{sports.streak=0;save.spelling.currentStreak=0;api.sfx.wrong();$('#spell-feedback').textContent=sports.tries===1?'ALMOST! TRY AGAIN.':`LOOK: ${sports.word.word.toUpperCase()}`;if(sports.tries>=2)setTimeout(()=>{updateWordMastery(sports.word,false);beginSport()},1000);else{sports.built='';sports.used=[];renderSpelling()}persist()}}
function updateWordMastery(word,success){const r=save.spelling.wordMastery[word.word]||{state:'NEW',successes:0,attempts:0,lastEvent:-9};r.attempts++;if(success&&r.lastEvent!==sports.index){r.successes++;r.lastEvent=sports.index}if(r.successes>=3)r.state='MASTERED';else if(r.successes>=2)r.state='CHALLENGE';else if(r.successes>=1)r.state='PRACTICING';if(!success&&r.state==='MASTERED')r.state='CHALLENGE';save.spelling.wordMastery[word.word]=r;save.spelling.wordsMastered=Object.values(save.spelling.wordMastery).filter(x=>x.state==='MASTERED').length;persist();if(save.spelling.wordsMastered>=10)unlock('words10');if(save.spelling.wordsMastered>=50)unlock('words50');if(save.spelling.wordsMastered>=100)unlock('words100')}
function speak(text){if(!('speechSynthesis'in window)){ $('#spell-feedback').textContent='Audio is not available. Use the word clue.';return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';const voices=speechSynthesis.getVoices(),voice=voices.find(v=>v.lang==='en-US')||voices.find(v=>v.lang.startsWith('en'));if(voice)u.voice=voice;u.rate=.82;u.pitch=1.03;speechSynthesis.speak(u)}
function speakWord(){speak(sports.word.word)}
$('#listen-word').onclick=speakWord;$('#hear-sentence').onclick=()=>speak(sports.word.sentence.replace(new RegExp(sports.word.word,'ig'),'this word'));
$('#spell-hint').onclick=()=>{sports.hinted=true;$('#spell-feedback').textContent=`HINT: ${sports.word.skill.replaceAll('-',' ').toUpperCase()} • ${sports.word.word.length} LETTERS`;speakWord()};
$('#spell-undo').onclick=()=>{if(!sports.built)return;const i=sports.used.pop();sports.built=sports.built.slice(0,-1);renderSpelling()};
$('#spell-skip').onclick=()=>{updateWordMastery(sports.word,false);beginSport()};

function beginSport(){sports.playing=true;$('#spelling-panel').classList.add('hidden');const sport=eventSport(),labels={basketball:'SHOOT',soccer:'KICK',football:'PASS',baseball:'SWING'};$('#sports-action').textContent=labels[sport]||'PLAY';$('#sports-action').classList.remove('hidden');sports.phase=0;drawSport();sports.raf=requestAnimationFrame(sportLoop);organPhrase(sport)}
function sportLoop(){if(!sports?.playing)return;sports.phase=(sports.phase+.018)%(Math.PI*2);drawSport();sports.raf=requestAnimationFrame(sportLoop)}
function drawSport(){const c=$('#sports-canvas'),x=c.getContext('2d'),w=c.width,h=c.height,sport=eventSport(),power=sports.power;x.clearRect(0,0,w,h);const g=x.createLinearGradient(0,0,0,h);g.addColorStop(0,'#102c61');g.addColorStop(1,'#07121f');x.fillStyle=g;x.fillRect(0,0,w,h);x.fillStyle='#173a55';for(let i=0;i<12;i++)x.fillRect(i*82,70+(i%3)*12,62,85);x.fillStyle='#dff7ff';x.font='900 24px system-ui';x.textAlign='center';x.fillText(EVENTS[sports.index][0],w/2,42);x.fillStyle='#ffe044';x.font='900 18px system-ui';x.fillText(power?'⚡ POWER PLAY READY!':'PLAY FOR YOUR TEAM!',w/2,72);
 if(sport==='basketball'){x.fillStyle='#b96b25';x.beginPath();x.arc(180,390,34,0,7);x.fill();x.strokeStyle='#ff5c5c';x.lineWidth=10;x.strokeRect(700,175,135,95);x.strokeStyle='#fff';x.lineWidth=6;x.beginPath();x.ellipse(720,292,54,12,0,0,7);x.stroke();drawTiming(x,w,h,power,'LOW  •  GOOD  •  PERFECT  •  GOOD  •  LOW')}
 if(sport==='soccer'){x.strokeStyle='#fff';x.lineWidth=9;x.strokeRect(570,170,250,190);x.fillStyle='#2dbf69';x.fillRect(0,360,w,140);const target=620+(Math.sin(sports.phase)*.5+.5)*150;x.fillStyle='#ffe044';x.beginPath();x.arc(target,255,power?54:38,0,7);x.fill();x.font='70px system-ui';x.fillText('⚽',170,420)}
 if(sport==='football'){x.fillStyle='#2f9c50';x.fillRect(0,110,w,390);for(let y=150;y<500;y+=70){x.fillStyle='#ffffff66';x.fillRect(0,y,w,3)}const open=Math.sin(sports.phase)>0?1:0;[0,1,2].slice(0,sports.index<5?2:3).forEach((n,i)=>{x.fillStyle=i===open?'#ffe044':'#05d9ff';x.beginPath();x.arc(590+i*105,230+i*65,30,0,7);x.fill();x.fillStyle='#fff';x.fillText(i===open?'OPEN!':'',590+i*105,185+i*65)});x.font='70px system-ui';x.fillText('🏈',170,420)}
 if(sport==='baseball'){x.fillStyle='#369b54';x.fillRect(0,110,w,390);x.fillStyle='#c49358';x.beginPath();x.moveTo(450,190);x.lineTo(700,430);x.lineTo(450,500);x.lineTo(200,430);x.closePath();x.fill();const px=690-(Math.sin(sports.phase)*.5+.5)*500;x.font='44px system-ui';x.fillText('⚾',px,330);x.font='70px system-ui';x.fillText('🏏',145,420)}x.textAlign='start'}
function drawTiming(x,w,h,power,label){const left=190,width=520,pos=left+(Math.sin(sports.phase)*.5+.5)*width;x.fillStyle='#18243b';x.fillRect(left,440,width,28);x.fillStyle='#48d17b';x.fillRect(left+width*.28,440,width*.44,28);x.fillStyle='#ffe044';x.fillRect(left+width*(power?.43:.46),438,width*(power?.14:.08),32);x.fillStyle='#fff';x.fillRect(pos,432,6,44);x.fillStyle='#dff7ff';x.font='700 13px system-ui';x.textAlign='center';x.fillText(label,w/2,490)}
$('#sports-action').onclick=()=>{if(!sports.playing)return;sports.playing=false;cancelAnimationFrame(sports.raf);const sport=eventSport(),accuracy=(Math.sin(sports.phase)*.5+.5),good=sports.power||accuracy>.3&&accuracy<.7;const points=good?1:0;sports.score+=points;sports.stars+=points;$('#sports-action').classList.add('hidden');const names={basketball:good?'SWISH!':'NICE SHOT!',soccer:good?'GOAL!':'GREAT KICK!',football:good?'TOUCHDOWN!':'GREAT PASS!',baseball:good?(sports.power?'HOME RUN!':'GREAT HIT!'):'GOOD SWING!'};stadiumSfx(sport,good);drawCelebration(names[sport]);if(good){if(sport==='basketball')unlock('basketballStar');if(sport==='soccer')unlock('soccerStar');if(sport==='football')unlock('touchdownStar');if(sport==='baseball'&&sports.power)unlock('homeRunHero')}setTimeout(()=>{sports.round++;nextSpelling()},950)};
function drawCelebration(text){const c=$('#sports-canvas'),x=c.getContext('2d');x.fillStyle='#07182bdd';x.fillRect(220,175,460,150);x.fillStyle='#ffe044';x.textAlign='center';x.font='1000 52px system-ui';x.fillText(text,450,260);x.textAlign='start'}
function finishEvent(){const needed=sports.index===9?7:1,won=sports.stars>=needed,stars=sports.index===9?Math.min(12,sports.stars):Math.max(1,Math.min(3,sports.stars));save.spelling.events[sports.index+1]={stars,score:sports.score};if(won)save.spelling.event=Math.max(save.spelling.event,Math.min(10,sports.index+2));if(sports.index===9&&won){save.spelling.championships++;save.spelling.season++;[['trophies','Spelling Champion Cup'],['gear','Champion Headphones'],['cards','Stadium Share Card']].forEach(([kind,item])=>{if(!save.collection[kind].includes(item))save.collection[kind].push(item)});unlock('firstChampionship')}persist();$('#sports-result-icon').textContent=won?'🏆':'⭐';$('#sports-result-title').textContent=sports.index===9?(won?'SPELLING CHAMPION!':'GREAT GAME!'):'EVENT COMPLETE!';$('#sports-result-copy').textContent=won?`${stars} STARS • ${save.spelling.wordsMastered} WORDS MASTERED`:`YOU'RE ALMOST CHAMPION! TRY THE CHAMPIONSHIP AGAIN.`;$('#sports-result').classList.remove('hidden');api.setMusic('victory')}
$('#sports-next').onclick=()=>{api.setMusic('menu');api.show('spelling-map-screen');renderEventMap()};$('#sports-map-return').onclick=$('#sports-next').onclick;$('#sports-pause').onclick=()=>{sports.playing=false;cancelAnimationFrame(sports.raf);api.show('spelling-map-screen');renderEventMap()};

function crowd(type){if(!save.sfxOn)return;const notes=type==='open'?[196,247,294]:[392,523,659];notes.forEach((n,i)=>api.tone(n,.22,'sawtooth',.012,i*.08))}
function organPhrase(sport){const roots={basketball:330,soccer:294,football:262,baseball:349},r=roots[sport]||330;[r,r*1.25,r*1.5,r*2].forEach((n,i)=>api.tone(n,.17,'square',.018,i*.09))}
function stadiumSfx(sport,good){const roots={basketball:620,soccer:420,football:300,baseball:760};api.tone(roots[sport],.12,sport==='baseball'?'square':'triangle',.05);if(good)setTimeout(()=>crowd('score'),100)}

function coach(key,icon,title,text){const k=`coach_${key}`;if(save.tutorials[k])return;save.tutorials[k]=true;persist();$('#achievement-icon').textContent=icon;$('#achievement-name').textContent=title;$('#achievement-copy').textContent=text;$('#achievement-share').classList.add('hidden');$('#achievement-panel').classList.remove('hidden')}
$('#achievement-continue').onclick=()=>{$('#achievement-panel').classList.add('hidden');$('#achievement-share').classList.remove('hidden')};$('#achievement-share').onclick=()=>openShare('achievement');

function openHelp(){const active=$$('.screen').find(x=>x.classList.contains('active'))?.id||'home-screen',context=active.includes('spelling')?'sports':active.includes('profile')?'player':active.includes('map')||active.includes('game')?'city':'home';const tips={home:'Choose a world, or open Player to see your journey.',city:'Solve math to power bridges, safe paths, Shield, and Turbo.',sports:'Listen to the word, spell it, then make the sports play!',player:'Edit your look, see mastery, collection, and share progress.'};$('#context-help').innerHTML=`<strong>HELP FOR THIS SCREEN</strong><p>${tips[context]}</p>`;showHelp(context);$('#help-center').classList.remove('hidden')}
function showHelp(k){const d={city:'LEFT and RIGHT move. JUMP clears hazards. Math makes the path safer. Tap ? during a level for a quick tip.',sports:'LISTEN, choose or build letters, then SHOOT, KICK, PASS, or SWING. Hints never cause Game Over.',player:'Your nickname, avatar, achievements, mastery, trophies, gear, and cards stay on this device.',share:'Share an Invite, Achievement, or My Journey card through your device. Santi Arcade never reads contacts.',install:'Android: choose INSTALL when available. iPhone/iPad: tap Share, choose Add to Home Screen, then tap Add.'};$('#help-detail').textContent=d[k]||'Choose a topic.'}
$$('.global-help').forEach(b=>b.onclick=openHelp);$$('[data-help]').forEach(b=>b.onclick=()=>showHelp(b.dataset.help));$('#help-center-close').onclick=()=>$('#help-center').classList.add('hidden');

function openShare(type='progress'){shareType=type;drawShareCard(type);$('#share-card-panel').classList.remove('hidden')}
$$('.global-share').forEach(b=>b.onclick=()=>openShare('invite'));$$('[data-share-type]').forEach(b=>b.onclick=()=>{shareType=b.dataset.shareType;drawShareCard(shareType)});$('#share-card-close').onclick=()=>$('#share-card-panel').classList.add('hidden');
function drawShareCard(type){
 const c=$('#share-card-canvas'),x=c.getContext('2d'),g=x.createLinearGradient(0,0,1080,1080);
 g.addColorStop(0,type==='invite'?'#07182b':'#102b55');g.addColorStop(1,type==='achievement'?'#6d246f':'#07182b');x.fillStyle=g;x.fillRect(0,0,1080,1080);
 x.textAlign='center';x.fillStyle='#05d9ff';x.font='1000 76px system-ui';x.fillText('SANTI ARCADE',540,105);x.fillStyle='#ffe044';x.font='800 34px system-ui';x.fillText('PLAY • LEARN • LEVEL UP',540,160);
 const avatar=document.createElement('canvas');avatar.width=420;avatar.height=420;api.drawAvatar(avatar,save.player.avatar,1);x.drawImage(avatar,330,170,420,420);
 x.fillStyle='#fff';
 if(type==='progress'){const target=CitySeasons.continueTarget(save),seasonState=CitySeasons.state(save,target.season),cityStars=Object.values(save.city.seasons||{}).reduce((n,s)=>n+Object.values(s.levels||{}).reduce((a,l)=>a+(l.stars||0),0),0);x.font='1000 50px system-ui';x.fillText('MY JOURNEY',540,580);x.font='800 31px system-ui';x.fillText(`CITY QUEST • SEASON ${target.season} • LEVEL ${target.level}/10`,540,655);x.fillText(`MATH SKILLS MASTERED: ${masteredMath()}  •  STARS: ${cityStars}`,540,710);x.fillText(`SPELLING • ${save.spelling.wordsMastered} WORDS MASTERED`,540,785);x.fillText(`CHAMPIONSHIPS: ${save.city.championships+save.spelling.championships}  •  BEST STREAK: ${save.spelling.bestStreak}`,540,840)}
 else if(type==='achievement'&&lastAchievement){x.font='120px system-ui';x.fillText(lastAchievement.icon,540,600);x.font='1000 48px system-ui';x.fillText(lastAchievement.name,540,690);x.font='700 28px system-ui';x.fillText(lastAchievement.copy,540,750)}
 else{x.font='1000 50px system-ui';x.fillText('CITY QUEST',540,600);x.fillText('SPELLING CHAMPIONS',540,670);x.font='700 30px system-ui';x.fillText('SCAN TO PLAY',540,750);const qr=$('#qr-panel img');if(qr?.complete)x.drawImage(qr,440,780,200,200)}
 x.fillStyle='#dff7ff';x.font='700 26px system-ui';x.fillText('ptrvargas.github.io/santi-arcade/',540,1035);x.textAlign='start';
}
$('#share-card-action').onclick=async()=>{const c=$('#share-card-canvas'),blob=await new Promise(r=>c.toBlob(r,'image/png'));try{const file=typeof File==='function'?new File([blob],`santi-arcade-${shareType}.png`,{type:'image/png'}):null;if(file&&navigator.canShare?.({files:[file]}))await navigator.share({title:'Santi Arcade',text:'Play • Learn • Level Up',files:[file],url:'https://ptrvargas.github.io/santi-arcade/'});else if(navigator.share)await navigator.share({title:'Santi Arcade',text:'Play • Learn • Level Up',url:'https://ptrvargas.github.io/santi-arcade/'});else downloadCard(c)}catch(e){if(e.name!=='AbortError')downloadCard(c)}};
function downloadCard(c){const a=document.createElement('a');a.href=c.toDataURL('image/png');a.download=`santi-arcade-${shareType}.png`;a.click()}
$('#share-card-link').onclick=api.copyShareLink;

$('#credits-btn').onclick=()=>$('#credits-panel').classList.remove('hidden');$('#credits-close').onclick=()=>$('#credits-panel').classList.add('hidden');
function openInstall(){const ios=/iPad|iPhone|iPod/.test(navigator.userAgent);$('#install-steps').innerHTML=ios?'<ol><li>Tap Share ↗</li><li>Choose Add to Home Screen</li><li>Tap Add</li></ol>':'<p>Tap INSTALL when Chrome makes it available.</p>';$('#install-action').classList.toggle('hidden',ios||!api.installPrompt);$('#install-panel').classList.remove('hidden')}
$('#install-action').onclick=()=>$('#install-btn').click();$('#install-close').onclick=$('#install-later').onclick=()=>{$('#install-panel').classList.add('hidden');save.tutorials.installPromptDismissed=true;persist()};
$('#install-help-btn').onclick=openInstall;
document.querySelector('[data-help="install"]').addEventListener('dblclick',openInstall);
setTimeout(()=>{if(!api.standalone()&&!save.tutorials.installPromptDismissed)openInstall()},2500);

$$('.home-button').forEach(b=>b.onclick=()=>api.show('home-screen'));
syncPlatform();
})();
